<?php

return [
    'site.name' => 'MuraenaRF',
    'site.tagline' => 'Distributed RF signal control system',
    'nav.menu' => 'Menu',
    'nav.language' => 'Language',
    'nav.github' => 'GitHub',
    'nav.open' => 'Open section',
    'footer.description' => 'An open hardware and software project for RF distribution control.',
    'footer.navigation' => 'Navigation',
    'footer.project' => 'Project',
    'footer.rights' => 'All rights reserved.',
    'common.learn_more' => 'Learn more',
    'common.status_development' => 'Under development',

    'main.menu' => 'Home',
    'main.title' => 'RF signal control where an ordinary cable is no longer enough',
    'main.subtitle' => 'MuraenaRF combines a transmitter, addressable output modules and a WebUI into a single RF distribution control system.',
    'main.hero_primary' => 'Project architecture',
    'main.hero_secondary' => 'Contact the author',
    'main.about_title' => 'What is MuraenaRF',
    'main.about_text' => 'MuraenaRF is hardware and software platform for remote RF signal distribution control. Commands travel through the existing coaxial network, while each output module responds only to its assigned address.',
    'main.problem_title' => 'Project goal',
    'main.problem_text' => 'The system is intended for installations where individual subscriber lines must be enabled, disabled or rerouted without installing additional control wiring.',
    'main.architecture_title' => 'Three parts of one system',
    'main.tx_title' => 'MuraenaTX',
    'main.tx_text' => 'The head-end unit generates commands and injects them into the coaxial network.',
    'main.rx_title' => 'MuraenaRX',
    'main.rx_text' => 'An addressable output module controls eight subscriber taps.',
    'main.base_title' => 'MuraenaBase',
    'main.base_text' => 'A WebUI for addresses, commands, masks and transmitter state.',
    'main.features_title' => 'Core principles',
    'main.feature_1' => 'Control data transmitted through the existing coaxial network',
    'main.feature_2' => 'Individual addressing of output modules',
    'main.feature_3' => 'Independent output groups controlled by a bit mask',
    'main.feature_4' => 'Open hardware and software architecture',

    'tx.menu' => 'MuraenaTX',
    'tx.title' => 'MuraenaTX — head-end transmitter',
    'tx.subtitle' => 'Generates addressable control commands and injects them into the coaxial network.',
    'tx.purpose_title' => 'Purpose',
    'tx.purpose_text' => 'MuraenaTX is the central node of the system. It receives commands from MuraenaBase, encodes the address, command and output mask, and transmits the packet to output modules.',
    'tx.device_title' => 'Hardware',
    'tx.device_text' => 'The unit is based on an ESP32-C3 microcontroller and a CC1101 RF transceiver. Transmitter parameters and state are stored in non-volatile memory.',
    'tx.operation_title' => 'How it works',
    'tx.operation_text' => 'Each packet contains an output module address, a command code and an eight-bit mask. The transmitter can be enabled or disabled in software and restores the saved state after restart.',
    'tx.protocol_title' => 'Command format',
    'tx.protocol_example' => 'addr=0001 cmd=01 mask=11110000',

    'rx.menu' => 'MuraenaRX',
    'rx.title' => 'MuraenaRX — output module',
    'rx.subtitle' => 'A controllable splitter with eight subscriber taps.',
    'rx.purpose_title' => 'Purpose',
    'rx.purpose_text' => 'The output module is installed directly in the distribution network and controls RF signal delivery to eight independent subscriber lines.',
    'rx.device_title' => 'Hardware',
    'rx.device_text' => 'The module combines a command receiver, microcontroller, RF switches and a passive splitter section. Power and control data may share the same coaxial cable.',
    'rx.operation_title' => 'How it works',
    'rx.operation_text' => 'The module receives packets, verifies its address and applies the eight-bit mask. Each bit represents one subscriber tap.',
    'rx.outputs_title' => 'Eight controllable outputs',
    'rx.outputs_text' => 'Outputs can be switched independently or in groups with a single command, allowing fast reconfiguration of the distribution network.',

    'base.menu' => 'MuraenaBase',
    'base.title' => 'MuraenaBase — control panel',
    'base.subtitle' => 'A WebUI for configuring and monitoring MuraenaRF.',
    'base.purpose_title' => 'Purpose',
    'base.purpose_text' => 'MuraenaBase provides a single interface for controlling the transmitter and the table of output module addresses.',
    'base.functions_title' => 'Features',
    'base.function_1' => 'View and edit device addresses',
    'base.function_2' => 'Configure commands and bit masks',
    'base.function_3' => 'Enable and disable MuraenaTX',
    'base.function_4' => 'Display installation objects on a map',
    'base.technology_title' => 'Technology',
    'base.technology_text' => 'The panel is developed as a standalone WebUI application and communicates with the project hardware through its backend.',

    'contact.menu' => 'Contact',
    'contact.title' => 'Contact the author',
    'contact.subtitle' => 'Project questions, suggestions and technical cooperation.',
    'contact.author_title' => 'Project author',
    'contact.author_name' => 'Vitali Tumasheuski',
    'contact.email_title' => 'Email',
    'contact.email' => 'info@muraenarf.com',
    'contact.github_title' => 'Source code',
    'contact.github_text' => 'Project repositories are published on GitHub.',
];
